// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.4.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/account.dart';
import 'api/keys.dart';
import 'api/relay.dart';
import 'api/simple.dart';
import 'api/sync.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.13.0-beta.4';

  @override
  int get rustContentHash => -2114088968;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_workspace',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<List<bool>> crateApiRelayCheckRelayStatuses({
    required List<String> urls,
  });

  Future<List<String>> crateApiRelayDefaultRelays();

  Future<void> crateApiSyncDeleteAccountBackup({
    required String mnemonic,
    required List<String> relayUrls,
  });

  Future<RemoteAccount?> crateApiSyncFetchAccountBackup({
    required String mnemonic,
    required List<String> relayUrls,
  });

  Future<String> crateApiKeysGenerateMnemonic();

  String crateApiSimpleGreet({required String name});

  Future<void> crateApiSimpleInitApp();

  Future<Account?> crateApiAccountLoadAccount({required String storageDir});

  Future<RelayList> crateApiRelayLoadRelayList({required String storageDir});

  Future<void> crateApiSyncPublishAccountBackup({
    required String mnemonic,
    required List<String> relayUrls,
    required String displayName,
    required String statusMessage,
    required PlatformInt64 updatedAt,
  });

  Future<void> crateApiAccountSaveAccount({
    required String storageDir,
    required String displayName,
    required String statusMessage,
    String? avatarPath,
  });

  Future<void> crateApiAccountSaveAccountWithTimestamp({
    required String storageDir,
    required String displayName,
    required String statusMessage,
    String? avatarPath,
    required PlatformInt64 updatedAt,
  });

  Future<void> crateApiRelaySaveRelayList({
    required String storageDir,
    required List<String> urls,
  });

  Future<void> crateApiKeysValidateMnemonic({required String mnemonic});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<List<bool>> crateApiRelayCheckRelayStatuses({
    required List<String> urls,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_String(urls, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiRelayCheckRelayStatusesConstMeta,
        argValues: [urls],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRelayCheckRelayStatusesConstMeta =>
      const TaskConstMeta(
        debugName: "check_relay_statuses",
        argNames: ["urls"],
      );

  @override
  Future<List<String>> crateApiRelayDefaultRelays() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiRelayDefaultRelaysConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRelayDefaultRelaysConstMeta =>
      const TaskConstMeta(debugName: "default_relays", argNames: []);

  @override
  Future<void> crateApiSyncDeleteAccountBackup({
    required String mnemonic,
    required List<String> relayUrls,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(mnemonic, serializer);
          sse_encode_list_String(relayUrls, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSyncDeleteAccountBackupConstMeta,
        argValues: [mnemonic, relayUrls],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSyncDeleteAccountBackupConstMeta =>
      const TaskConstMeta(
        debugName: "delete_account_backup",
        argNames: ["mnemonic", "relayUrls"],
      );

  @override
  Future<RemoteAccount?> crateApiSyncFetchAccountBackup({
    required String mnemonic,
    required List<String> relayUrls,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(mnemonic, serializer);
          sse_encode_list_String(relayUrls, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_remote_account,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSyncFetchAccountBackupConstMeta,
        argValues: [mnemonic, relayUrls],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSyncFetchAccountBackupConstMeta =>
      const TaskConstMeta(
        debugName: "fetch_account_backup",
        argNames: ["mnemonic", "relayUrls"],
      );

  @override
  Future<String> crateApiKeysGenerateMnemonic() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiKeysGenerateMnemonicConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKeysGenerateMnemonicConstMeta =>
      const TaskConstMeta(debugName: "generate_mnemonic", argNames: []);

  @override
  String crateApiSimpleGreet({required String name}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGreetConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGreetConstMeta =>
      const TaskConstMeta(debugName: "greet", argNames: ["name"]);

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<Account?> crateApiAccountLoadAccount({required String storageDir}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(storageDir, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_account,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAccountLoadAccountConstMeta,
        argValues: [storageDir],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAccountLoadAccountConstMeta =>
      const TaskConstMeta(debugName: "load_account", argNames: ["storageDir"]);

  @override
  Future<RelayList> crateApiRelayLoadRelayList({required String storageDir}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(storageDir, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_relay_list,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiRelayLoadRelayListConstMeta,
        argValues: [storageDir],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRelayLoadRelayListConstMeta => const TaskConstMeta(
    debugName: "load_relay_list",
    argNames: ["storageDir"],
  );

  @override
  Future<void> crateApiSyncPublishAccountBackup({
    required String mnemonic,
    required List<String> relayUrls,
    required String displayName,
    required String statusMessage,
    required PlatformInt64 updatedAt,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(mnemonic, serializer);
          sse_encode_list_String(relayUrls, serializer);
          sse_encode_String(displayName, serializer);
          sse_encode_String(statusMessage, serializer);
          sse_encode_i_64(updatedAt, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSyncPublishAccountBackupConstMeta,
        argValues: [mnemonic, relayUrls, displayName, statusMessage, updatedAt],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSyncPublishAccountBackupConstMeta =>
      const TaskConstMeta(
        debugName: "publish_account_backup",
        argNames: [
          "mnemonic",
          "relayUrls",
          "displayName",
          "statusMessage",
          "updatedAt",
        ],
      );

  @override
  Future<void> crateApiAccountSaveAccount({
    required String storageDir,
    required String displayName,
    required String statusMessage,
    String? avatarPath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(storageDir, serializer);
          sse_encode_String(displayName, serializer);
          sse_encode_String(statusMessage, serializer);
          sse_encode_opt_String(avatarPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiAccountSaveAccountConstMeta,
        argValues: [storageDir, displayName, statusMessage, avatarPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAccountSaveAccountConstMeta => const TaskConstMeta(
    debugName: "save_account",
    argNames: ["storageDir", "displayName", "statusMessage", "avatarPath"],
  );

  @override
  Future<void> crateApiAccountSaveAccountWithTimestamp({
    required String storageDir,
    required String displayName,
    required String statusMessage,
    String? avatarPath,
    required PlatformInt64 updatedAt,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(storageDir, serializer);
          sse_encode_String(displayName, serializer);
          sse_encode_String(statusMessage, serializer);
          sse_encode_opt_String(avatarPath, serializer);
          sse_encode_i_64(updatedAt, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiAccountSaveAccountWithTimestampConstMeta,
        argValues: [
          storageDir,
          displayName,
          statusMessage,
          avatarPath,
          updatedAt,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAccountSaveAccountWithTimestampConstMeta =>
      const TaskConstMeta(
        debugName: "save_account_with_timestamp",
        argNames: [
          "storageDir",
          "displayName",
          "statusMessage",
          "avatarPath",
          "updatedAt",
        ],
      );

  @override
  Future<void> crateApiRelaySaveRelayList({
    required String storageDir,
    required List<String> urls,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(storageDir, serializer);
          sse_encode_list_String(urls, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiRelaySaveRelayListConstMeta,
        argValues: [storageDir, urls],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRelaySaveRelayListConstMeta => const TaskConstMeta(
    debugName: "save_relay_list",
    argNames: ["storageDir", "urls"],
  );

  @override
  Future<void> crateApiKeysValidateMnemonic({required String mnemonic}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(mnemonic, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiKeysValidateMnemonicConstMeta,
        argValues: [mnemonic],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKeysValidateMnemonicConstMeta =>
      const TaskConstMeta(
        debugName: "validate_mnemonic",
        argNames: ["mnemonic"],
      );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  Account dco_decode_account(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return Account(
      displayName: dco_decode_String(arr[0]),
      statusMessage: dco_decode_String(arr[1]),
      avatarPath: dco_decode_opt_String(arr[2]),
      updatedAt: dco_decode_i_64(arr[3]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  Account dco_decode_box_autoadd_account(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_account(raw);
  }

  @protected
  RemoteAccount dco_decode_box_autoadd_remote_account(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_remote_account(raw);
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<bool> dco_decode_list_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_bool).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  Account? dco_decode_opt_box_autoadd_account(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_account(raw);
  }

  @protected
  RemoteAccount? dco_decode_opt_box_autoadd_remote_account(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_remote_account(raw);
  }

  @protected
  RelayList dco_decode_relay_list(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 1)
      throw Exception('unexpected arr length: expect 1 but see ${arr.length}');
    return RelayList(urls: dco_decode_list_String(arr[0]));
  }

  @protected
  RemoteAccount dco_decode_remote_account(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return RemoteAccount(
      displayName: dco_decode_String(arr[0]),
      statusMessage: dco_decode_String(arr[1]),
      updatedAt: dco_decode_i_64(arr[2]),
    );
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  Account sse_decode_account(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_displayName = sse_decode_String(deserializer);
    var var_statusMessage = sse_decode_String(deserializer);
    var var_avatarPath = sse_decode_opt_String(deserializer);
    var var_updatedAt = sse_decode_i_64(deserializer);
    return Account(
      displayName: var_displayName,
      statusMessage: var_statusMessage,
      avatarPath: var_avatarPath,
      updatedAt: var_updatedAt,
    );
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  Account sse_decode_box_autoadd_account(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_account(deserializer));
  }

  @protected
  RemoteAccount sse_decode_box_autoadd_remote_account(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_remote_account(deserializer));
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<bool> sse_decode_list_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <bool>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_bool(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  Account? sse_decode_opt_box_autoadd_account(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_account(deserializer));
    } else {
      return null;
    }
  }

  @protected
  RemoteAccount? sse_decode_opt_box_autoadd_remote_account(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_remote_account(deserializer));
    } else {
      return null;
    }
  }

  @protected
  RelayList sse_decode_relay_list(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_urls = sse_decode_list_String(deserializer);
    return RelayList(urls: var_urls);
  }

  @protected
  RemoteAccount sse_decode_remote_account(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_displayName = sse_decode_String(deserializer);
    var var_statusMessage = sse_decode_String(deserializer);
    var var_updatedAt = sse_decode_i_64(deserializer);
    return RemoteAccount(
      displayName: var_displayName,
      statusMessage: var_statusMessage,
      updatedAt: var_updatedAt,
    );
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_account(Account self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.displayName, serializer);
    sse_encode_String(self.statusMessage, serializer);
    sse_encode_opt_String(self.avatarPath, serializer);
    sse_encode_i_64(self.updatedAt, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_account(Account self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_account(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_remote_account(
    RemoteAccount self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_remote_account(self, serializer);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_bool(List<bool> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_bool(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_account(
    Account? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_account(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_remote_account(
    RemoteAccount? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_remote_account(self, serializer);
    }
  }

  @protected
  void sse_encode_relay_list(RelayList self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_String(self.urls, serializer);
  }

  @protected
  void sse_encode_remote_account(RemoteAccount self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.displayName, serializer);
    sse_encode_String(self.statusMessage, serializer);
    sse_encode_i_64(self.updatedAt, serializer);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
