[package]
name = "rust_lib_workspace"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
flutter_rust_bridge = "=2.13.0-beta.4"
nostr = { version = "0.44.4", features = ["nip44", "nip49", "nip59"] }
nostr-database = "0.44.0"
nostr-lmdb = "0.44.1"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(frb_expand)'] }
