// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.4.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `db`, `decrypt_seal`, `load_read_state`, `read_state_path`, `receive_gift_wrap`, `save_read_state`

/// Builds a Gift Wrap for `message` addressed to `friend_pubkey`, persists
/// our own copy of the `Seal` locally (so our own sent messages show up in
/// [load_chat_history] too), and publishes the wrap to the friend's relays.
Future<void> sendChatMessage({
  required String mnemonic,
  required String storageDir,
  required String friendPubkey,
  required String message,
}) => RustLib.instance.api.crateApiChatSendChatMessage(
  mnemonic: mnemonic,
  storageDir: storageDir,
  friendPubkey: friendPubkey,
  message: message,
);

/// Loads the full decrypted message history with `friend_pubkey` from
/// local storage (no relay round-trip — the live subscription and
/// [send_chat_message] are what keep it current), oldest first.
Future<List<ChatMessage>> loadChatHistory({
  required String mnemonic,
  required String storageDir,
  required String friendPubkey,
}) => RustLib.instance.api.crateApiChatLoadChatHistory(
  mnemonic: mnemonic,
  storageDir: storageDir,
  friendPubkey: friendPubkey,
);

/// Marks every message currently in `friend_pubkey`'s thread as read —
/// call when the user opens that thread.
Future<void> markThreadRead({
  required String storageDir,
  required String friendPubkey,
}) => RustLib.instance.api.crateApiChatMarkThreadRead(
  storageDir: storageDir,
  friendPubkey: friendPubkey,
);

/// For each of `friend_pubkeys`, counts messages from that friend received
/// after the last time [mark_thread_read] was called for them (or all of
/// their messages, if the thread has never been opened).
Future<List<UnreadCount>> loadUnreadCounts({
  required String mnemonic,
  required String storageDir,
  required List<String> friendPubkeys,
}) => RustLib.instance.api.crateApiChatLoadUnreadCounts(
  mnemonic: mnemonic,
  storageDir: storageDir,
  friendPubkeys: friendPubkeys,
);

/// A single decrypted message, ready to show in the UI.
class ChatMessage {
  final String id;
  final String senderPubkey;
  final String content;
  final PlatformInt64 createdAt;
  final bool isMine;

  const ChatMessage({
    required this.id,
    required this.senderPubkey,
    required this.content,
    required this.createdAt,
    required this.isMine,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      senderPubkey.hashCode ^
      content.hashCode ^
      createdAt.hashCode ^
      isMine.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChatMessage &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          senderPubkey == other.senderPubkey &&
          content == other.content &&
          createdAt == other.createdAt &&
          isMine == other.isMine;
}

class UnreadCount {
  final String friendPubkey;
  final int count;

  const UnreadCount({required this.friendPubkey, required this.count});

  @override
  int get hashCode => friendPubkey.hashCode ^ count.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UnreadCount &&
          runtimeType == other.runtimeType &&
          friendPubkey == other.friendPubkey &&
          count == other.count;
}
