// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.4.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `config_path`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`

/// Saves the app config as JSON under `storage_dir`. `storage_dir` must
/// already exist (e.g. the app's documents directory, resolved on the
/// Dart side via path_provider).
Future<void> saveConfig({
  required String storageDir,
  required AppConfig config,
}) => RustLib.instance.api.crateApiConfigSaveConfig(
  storageDir: storageDir,
  config: config,
);

/// Loads the saved app config, or defaults (follow device locale) if none
/// has been saved yet.
Future<AppConfig> loadConfig({required String storageDir}) =>
    RustLib.instance.api.crateApiConfigLoadConfig(storageDir: storageDir);

/// Personal app preferences — never shared with friends (unlike
/// `relays.json`, whose contents are deliberately included in the
/// friend-facing payloads so friends know where to reach us). Synced only
/// through this account's own self-encrypted backup slot.
class AppConfig {
  /// BCP-47 language code (e.g. "en", "ja"), or `None` to follow the
  /// device locale.
  final String? language;

  const AppConfig({this.language});

  static Future<AppConfig> default_() =>
      RustLib.instance.api.crateApiConfigAppConfigDefault();

  @override
  int get hashCode => language.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppConfig &&
          runtimeType == other.runtimeType &&
          language == other.language;
}
