// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.4.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `blocked_path`, `friends_path`, `load_blocked`, `now`, `save_friends_list`, `update_friend_profile`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`

/// Loads the saved friends list, or an empty list if none has been saved yet.
Future<List<Friend>> loadFriends({required String storageDir}) =>
    RustLib.instance.api.crateApiFriendsLoadFriends(storageDir: storageDir);

/// Adds (or updates the info of) a friend, deduplicating by their contact
/// pubkey.
Future<void> addFriend({
  required String storageDir,
  required String pubkey,
  required int myAccountIndex,
  required String displayName,
  required String statusMessage,
  required List<String> relays,
  String? avatarPath,
}) => RustLib.instance.api.crateApiFriendsAddFriend(
  storageDir: storageDir,
  pubkey: pubkey,
  myAccountIndex: myAccountIndex,
  displayName: displayName,
  statusMessage: statusMessage,
  relays: relays,
  avatarPath: avatarPath,
);

/// Sets whether a friend is pinned as a favorite. A no-op if there's no
/// friend with that pubkey.
Future<void> setFavoriteFriend({
  required String storageDir,
  required String pubkey,
  required bool isFavorite,
}) => RustLib.instance.api.crateApiFriendsSetFavoriteFriend(
  storageDir: storageDir,
  pubkey: pubkey,
  isFavorite: isFavorite,
);

/// Removes a friend by their contact pubkey (e.g. after they're blocked).
Future<void> removeFriend({
  required String storageDir,
  required String pubkey,
}) => RustLib.instance.api.crateApiFriendsRemoveFriend(
  storageDir: storageDir,
  pubkey: pubkey,
);

/// Permanently blocks a contact pubkey — e.g. after rejecting their friend
/// request, so re-sending it (with the same leaked/reused key) has no effect.
Future<void> blockPubkey({
  required String storageDir,
  required String pubkey,
}) => RustLib.instance.api.crateApiFriendsBlockPubkey(
  storageDir: storageDir,
  pubkey: pubkey,
);

/// A confirmed friend: their per-relationship contact pubkey, and which of
/// *our own* NIP-06 account indices we use to talk to them (see
/// `keys::derive_contact_keys`). Every friend has a distinct pair of keys
/// on both sides, so leaking one relationship's key never exposes another.
class Friend {
  /// The friend's contact pubkey (hex) — distinct from their account's
  /// core identity, minted specifically for this relationship.
  final String pubkey;

  /// Which of our own `account` indices we use to talk to this friend.
  final int myAccountIndex;
  final String displayName;
  final String statusMessage;

  /// The friend's relays as of the last time we heard from them — where
  /// we publish future profile updates to.
  final List<String> relays;

  /// Local file path to the friend's avatar image, as last received —
  /// downloaded and cached on this device, not a remote URL.
  final String? avatarPath;
  final PlatformInt64 addedAt;

  /// User-set flag to pin this friend near the top of the friends list.
  final bool isFavorite;

  const Friend({
    required this.pubkey,
    required this.myAccountIndex,
    required this.displayName,
    required this.statusMessage,
    required this.relays,
    this.avatarPath,
    required this.addedAt,
    required this.isFavorite,
  });

  @override
  int get hashCode =>
      pubkey.hashCode ^
      myAccountIndex.hashCode ^
      displayName.hashCode ^
      statusMessage.hashCode ^
      relays.hashCode ^
      avatarPath.hashCode ^
      addedAt.hashCode ^
      isFavorite.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Friend &&
          runtimeType == other.runtimeType &&
          pubkey == other.pubkey &&
          myAccountIndex == other.myAccountIndex &&
          displayName == other.displayName &&
          statusMessage == other.statusMessage &&
          relays == other.relays &&
          avatarPath == other.avatarPath &&
          addedAt == other.addedAt &&
          isFavorite == other.isFavorite;
}
