// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.4.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `already_processed`, `group_ratchet_lock`, `identity_accounts_path`, `load_identity_accounts`, `load_sessions`, `mark_processed`, `own_group_identities`, `own_group_keys`, `processed_ids_path`, `receive_gift_wrap`, `save_identity_accounts`, `save_sessions`, `send_to_member`, `session_key`, `sessions_path`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<GroupRatchetReceived>>
abstract class GroupRatchetReceived implements RustOpaqueInterface {
  PlatformInt64 get createdAt;

  String get id;

  Kind get kind;

  String get plaintext;

  String get senderGroupPubkey;

  set createdAt(PlatformInt64 createdAt);

  set id(String id);

  set kind(Kind kind);

  set plaintext(String plaintext);

  set senderGroupPubkey(String senderGroupPubkey);
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Kind>>
abstract class Kind implements RustOpaqueInterface {}
