// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.4.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'attachment.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `append_message`, `apply_group_ratchet_received`, `broadcast_membership_async`, `broadcast_membership`, `delete_group_messages`, `deliver_to_member`, `groups_path`, `load_all_messages`, `maybe_self_announce_async`, `merge_roster`, `messages_path`, `now`, `own_member_entry`, `receive_group_gift_wrap`, `resolve_member_uid_by_group_pubkey`, `resolve_members`, `save_groups`, `self_display_name`, `send_sealed`, `store_received_group_message`, `upload_and_send_group_attachment`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `GroupAttachmentPayload`, `GroupInvitePayload`, `GroupMessagePayload`, `GroupReceived`, `StoredGroupAttachment`, `StoredGroupMessage`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `eq`

Future<List<Group>> loadGroups({required String storageDir}) =>
    RustLib.instance.api.crateApiGroupsLoadGroups(storageDir: storageDir);

/// Creates a group named `name` with `member_pubkeys` (each must already be
/// a friend — see [resolve_members]) plus this account itself, persists it
/// locally, and broadcasts a [GROUP_INVITE_KIND] invite to each member (see
/// module doc for the two delivery channels tried). `ratchet_key` is
/// `None` before this account has one yet (see [own_member_entry]).
Future<Group> createGroup({
  required String mnemonic,
  required String storageDir,
  required String name,
  required List<String> memberPubkeys,
  String? ratchetKey,
}) => RustLib.instance.api.crateApiGroupsCreateGroup(
  mnemonic: mnemonic,
  storageDir: storageDir,
  name: name,
  memberPubkeys: memberPubkeys,
  ratchetKey: ratchetKey,
);

/// Adds `member_pubkey` (must already be a friend) to `group_id`'s member
/// list and re-broadcasts the full updated list to every member (the new
/// one included, so they learn the group's name and existing members in
/// the same message).
Future<Group> addGroupMember({
  required String mnemonic,
  required String storageDir,
  required String groupId,
  required String memberPubkey,
  String? ratchetKey,
}) => RustLib.instance.api.crateApiGroupsAddGroupMember(
  mnemonic: mnemonic,
  storageDir: storageDir,
  groupId: groupId,
  memberPubkey: memberPubkey,
  ratchetKey: ratchetKey,
);

/// This device's message history for `group_id`, oldest first. Like
/// `ratchet.rs`'s history, only ever grows via messages sent/received *by
/// this specific device* — there's no group-wide event log to backfill
/// from, since every member sees a different set of Gift Wraps.
Future<List<GroupChatMessage>> loadGroupMessages({
  required String mnemonic,
  required String storageDir,
  required String groupId,
}) => RustLib.instance.api.crateApiGroupsLoadGroupMessages(
  mnemonic: mnemonic,
  storageDir: storageDir,
  groupId: groupId,
);

/// Sends `content` to every member of `group_id` (see module doc for the
/// two delivery channels tried, in order) and appends it to this device's
/// own local history. `ratchet_key` is `None` on a fresh install before
/// this device's own local storage key exists yet, in which case every
/// member gets the (non-forward-secret) 1:1-fallback copy, same as before
/// forward secrecy existed.
Future<void> sendGroupMessage({
  required String mnemonic,
  required String storageDir,
  required String groupId,
  required String content,
  String? ratchetKey,
}) => RustLib.instance.api.crateApiGroupsSendGroupMessage(
  mnemonic: mnemonic,
  storageDir: storageDir,
  groupId: groupId,
  content: content,
  ratchetKey: ratchetKey,
);

/// Removes the member with `uid` from `group_id`'s roster, saves, and
/// re-broadcasts the updated roster to the remaining members — the removed
/// member naturally stops receiving anything since they're no longer in
/// `group.members`. No key-rotation/PCS-on-removal — out of scope, same
/// best-effort simplicity as the rest of this module. Any existing member
/// can call this (same trust model as [add_group_member]).
Future<Group> removeGroupMember({
  required String mnemonic,
  required String storageDir,
  required String groupId,
  required String memberUid,
  String? ratchetKey,
}) => RustLib.instance.api.crateApiGroupsRemoveGroupMember(
  mnemonic: mnemonic,
  storageDir: storageDir,
  groupId: groupId,
  memberUid: memberUid,
  ratchetKey: ratchetKey,
);

/// Removes this account's own entry from `group_id`'s roster, broadcasts
/// the updated (self-excluded) roster to the remaining members so they see
/// the departure, then deletes the group and its local message history
/// from this device.
Future<void> leaveGroup({
  required String mnemonic,
  required String storageDir,
  required String groupId,
  String? ratchetKey,
}) => RustLib.instance.api.crateApiGroupsLeaveGroup(
  mnemonic: mnemonic,
  storageDir: storageDir,
  groupId: groupId,
  ratchetKey: ratchetKey,
);

/// Encrypts and uploads `file_path` once (via `attachment.rs`'s shared
/// primitives — see that module's doc comment for the encryption scheme),
/// then delivers a [GroupAttachmentPayload] pointer to every member of
/// `group_id` (see module doc for the two delivery channels tried) and
/// appends the message to this device's own local history. Streams
/// progress/terminal events on `sink`, mirroring
/// `attachment::send_chat_attachment`.
Stream<AttachmentUploadEvent> sendGroupAttachment({
  required String mnemonic,
  required String storageDir,
  required String groupId,
  required String filePath,
  required String mimeType,
  String? caption,
  String? ratchetKey,
  String? serverOverride,
}) => RustLib.instance.api.crateApiGroupsSendGroupAttachment(
  mnemonic: mnemonic,
  storageDir: storageDir,
  groupId: groupId,
  filePath: filePath,
  mimeType: mimeType,
  caption: caption,
  ratchetKey: ratchetKey,
  serverOverride: serverOverride,
);

/// Downloads and decrypts a group attachment — mirrors
/// `attachment::download_chat_attachment`, but caches under a
/// group-scoped path (collision-free against the 1:1 cache) and skips the
/// NIP-44 unwrap of `enc_key` (base64-decoded directly instead — see
/// [GroupAttachmentPayload]'s doc comment on the asymmetry).
Future<String> downloadGroupAttachment({
  required String storageDir,
  required String groupId,
  required String messageId,
  required String url,
  required String encKey,
}) => RustLib.instance.api.crateApiGroupsDownloadGroupAttachment(
  storageDir: storageDir,
  groupId: groupId,
  messageId: messageId,
  url: url,
  encKey: encKey,
);

class Group {
  final String id;
  final String name;
  final List<GroupMember> members;
  final PlatformInt64 createdAt;

  const Group({
    required this.id,
    required this.name,
    required this.members,
    required this.createdAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^ name.hashCode ^ members.hashCode ^ createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Group &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          members == other.members &&
          createdAt == other.createdAt;
}

/// An image/file attachment resolved from a [GroupAttachmentPayload],
/// exposed on [GroupChatMessage] — mirrors `chat.rs`'s `ChatAttachment`.
class GroupChatAttachment {
  final String url;
  final String sha256;
  final int size;
  final String mimeType;
  final String filename;
  final String encKey;
  final String? caption;

  const GroupChatAttachment({
    required this.url,
    required this.sha256,
    required this.size,
    required this.mimeType,
    required this.filename,
    required this.encKey,
    this.caption,
  });

  @override
  int get hashCode =>
      url.hashCode ^
      sha256.hashCode ^
      size.hashCode ^
      mimeType.hashCode ^
      filename.hashCode ^
      encKey.hashCode ^
      caption.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GroupChatAttachment &&
          runtimeType == other.runtimeType &&
          url == other.url &&
          sha256 == other.sha256 &&
          size == other.size &&
          mimeType == other.mimeType &&
          filename == other.filename &&
          encKey == other.encKey &&
          caption == other.caption;
}

class GroupChatMessage {
  final String id;
  final String groupId;
  final String senderUid;
  final String senderName;
  final String content;
  final PlatformInt64 createdAt;
  final bool isMine;
  final GroupChatAttachment? attachment;

  const GroupChatMessage({
    required this.id,
    required this.groupId,
    required this.senderUid,
    required this.senderName,
    required this.content,
    required this.createdAt,
    required this.isMine,
    this.attachment,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      groupId.hashCode ^
      senderUid.hashCode ^
      senderName.hashCode ^
      content.hashCode ^
      createdAt.hashCode ^
      isMine.hashCode ^
      attachment.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GroupChatMessage &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          groupId == other.groupId &&
          senderUid == other.senderUid &&
          senderName == other.senderName &&
          content == other.content &&
          createdAt == other.createdAt &&
          isMine == other.isMine &&
          attachment == other.attachment;
}

class GroupMember {
  final String uid;
  final String displayName;

  /// This member's dedicated per-group Nostr routing identity (hex
  /// pubkey) — see `group_ratchet.rs`'s module doc. `None` until they've
  /// announced it (self-reported the first time their own device
  /// processes this group). Once set, messages/roster-updates to them go
  /// directly here — unlike the original friend-relationship channel,
  /// this doesn't require `self` to actually be their 1:1 friend.
  final String? groupPubkey;

  /// Where to publish to [group_pubkey] — this member's own relay list,
  /// self-reported alongside it.
  final List<String> relays;

  /// This member's forward-secrecy device key bundle (the same one
  /// `ratchet.rs` announces for 1:1 — see that module's doc comment),
  /// needed to bootstrap this group's pairwise Olm session with them
  /// (see `group_ratchet.rs`). Opaque here; only `ratchet.rs` parses it.
  final String? devicePubkey;

  const GroupMember({
    required this.uid,
    required this.displayName,
    this.groupPubkey,
    required this.relays,
    this.devicePubkey,
  });

  static Future<GroupMember> default_() =>
      RustLib.instance.api.crateApiGroupsGroupMemberDefault();

  @override
  int get hashCode =>
      uid.hashCode ^
      displayName.hashCode ^
      groupPubkey.hashCode ^
      relays.hashCode ^
      devicePubkey.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GroupMember &&
          runtimeType == other.runtimeType &&
          uid == other.uid &&
          displayName == other.displayName &&
          groupPubkey == other.groupPubkey &&
          relays == other.relays &&
          devicePubkey == other.devicePubkey;
}
