// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.4.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `allocate_account_index`, `invites_path`, `load_file`, `next_account_index`, `now`, `save_file`, `set_invites_snapshot`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `InvitesFile`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`
// These functions are ignored (category: IgnoreBecauseOwnerTyShouldIgnore): `default`

/// Creates a new invite with a freshly-allocated `account` index, never
/// reused even if this invite is later revoked or expires.
///
/// `ttl_seconds`: `None` for no expiry. `max_uses`: `None` for unlimited.
Future<Invite> createInvite({
  required String storageDir,
  PlatformInt64? ttlSeconds,
  int? maxUses,
}) => RustLib.instance.api.crateApiInvitesCreateInvite(
  storageDir: storageDir,
  ttlSeconds: ttlSeconds,
  maxUses: maxUses,
);

/// Lists all invites (active and inactive) this device has created.
Future<List<Invite>> listInvites({required String storageDir}) =>
    RustLib.instance.api.crateApiInvitesListInvites(storageDir: storageDir);

/// Lists only currently-usable invites (not revoked, not expired, not
/// over their use limit) — the ones that should be polled for incoming
/// friend requests.
Future<List<Invite>> listActiveInvites({required String storageDir}) => RustLib
    .instance
    .api
    .crateApiInvitesListActiveInvites(storageDir: storageDir);

/// Marks an invite as revoked so it's no longer polled for requests, even
/// if not expired or used up yet.
Future<void> revokeInvite({
  required String storageDir,
  required int accountIndex,
}) => RustLib.instance.api.crateApiInvitesRevokeInvite(
  storageDir: storageDir,
  accountIndex: accountIndex,
);

/// Records that an invite was used (a friend request against it was
/// accepted), incrementing its use count.
Future<void> recordInviteUse({
  required String storageDir,
  required int accountIndex,
}) => RustLib.instance.api.crateApiInvitesRecordInviteUse(
  storageDir: storageDir,
  accountIndex: accountIndex,
);

/// A single-use-or-limited-use invite: a dedicated NIP-06 `account` index
/// (see `keys::derive_contact_keys`) shown as a QR code, that a scanning
/// friend sends their friend request to. Kept separate from the account's
/// core identity so a leaked invite only exposes itself, never other
/// friends or the account backup identity (account 0).
class Invite {
  final int accountIndex;
  final PlatformInt64 createdAt;

  /// `None` means no expiry.
  final PlatformInt64? expiresAt;

  /// `None` means unlimited uses.
  final int? maxUses;
  final int useCount;
  final bool revoked;

  const Invite({
    required this.accountIndex,
    required this.createdAt,
    this.expiresAt,
    this.maxUses,
    required this.useCount,
    required this.revoked,
  });

  Future<bool> isActive({required PlatformInt64 now}) =>
      RustLib.instance.api.crateApiInvitesInviteIsActive(that: this, now: now);

  @override
  int get hashCode =>
      accountIndex.hashCode ^
      createdAt.hashCode ^
      expiresAt.hashCode ^
      maxUses.hashCode ^
      useCount.hashCode ^
      revoked.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Invite &&
          runtimeType == other.runtimeType &&
          accountIndex == other.accountIndex &&
          createdAt == other.createdAt &&
          expiresAt == other.expiresAt &&
          maxUses == other.maxUses &&
          useCount == other.useCount &&
          revoked == other.revoked;
}
