// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.4.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `attr`, `decode_entities`, `fetch_link_preview_async`, `html_tags`, `parse_meta`, `resolve_url`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`

/// Fetches `url` and extracts Open Graph (falling back to plain HTML) page
/// metadata for an inline preview card. Errors (network failure, non-HTML
/// response, no usable metadata at all) are returned as `Err` so the caller
/// can just skip showing a card rather than showing an empty one.
Future<LinkPreview> fetchLinkPreview({required String url}) =>
    RustLib.instance.api.crateApiLinkPreviewFetchLinkPreview(url: url);

/// First `http(s)://` URL found in free-form message text, or `None` — used
/// by the chat thread to decide whether to show a preview card at all.
Future<String?> extractFirstUrl({required String text}) =>
    RustLib.instance.api.crateApiLinkPreviewExtractFirstUrl(text: text);

class LinkPreview {
  final String url;
  final String? title;
  final String? description;
  final String? imageUrl;
  final String? siteName;

  const LinkPreview({
    required this.url,
    this.title,
    this.description,
    this.imageUrl,
    this.siteName,
  });

  static Future<LinkPreview> default_() =>
      RustLib.instance.api.crateApiLinkPreviewLinkPreviewDefault();

  @override
  int get hashCode =>
      url.hashCode ^
      title.hashCode ^
      description.hashCode ^
      imageUrl.hashCode ^
      siteName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LinkPreview &&
          runtimeType == other.runtimeType &&
          url == other.url &&
          title == other.title &&
          description == other.description &&
          imageUrl == other.imageUrl &&
          siteName == other.siteName;
}
