// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.4.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `profile_path`

/// Saves the profile as JSON under `storage_dir`.
/// `storage_dir` must already exist (e.g. the app's documents directory,
/// resolved on the Dart side via path_provider).
Future<void> saveProfile({
  required String storageDir,
  required String displayName,
  required String statusMessage,
  String? avatarPath,
}) => RustLib.instance.api.crateApiProfileSaveProfile(
  storageDir: storageDir,
  displayName: displayName,
  statusMessage: statusMessage,
  avatarPath: avatarPath,
);

/// Loads a previously saved profile, or `None` if none has been saved yet.
Future<Profile?> loadProfile({required String storageDir}) =>
    RustLib.instance.api.crateApiProfileLoadProfile(storageDir: storageDir);

/// Local display profile. KeyChat has no fixed account key, so this is the
/// only per-device identity data that needs to be persisted.
class Profile {
  final String displayName;
  final String statusMessage;

  /// Absolute path to the avatar image file, if the user picked one.
  final String? avatarPath;

  const Profile({
    required this.displayName,
    required this.statusMessage,
    this.avatarPath,
  });

  @override
  int get hashCode =>
      displayName.hashCode ^ statusMessage.hashCode ^ avatarPath.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Profile &&
          runtimeType == other.runtimeType &&
          displayName == other.displayName &&
          statusMessage == other.statusMessage &&
          avatarPath == other.avatarPath;
}
