// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.4.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `account_path`, `already_processed`, `append_message`, `base64_decode`, `base64_encode`, `decode`, `decrypt_at_rest`, `encode`, `encrypt_at_rest`, `forget_sessions_if_reinstalled`, `friend_devices_path`, `hex32`, `load_all_messages`, `load_friend_devices`, `load_or_create_account`, `load_sessions`, `mark_processed`, `messages_path`, `new`, `new`, `now`, `of`, `processed_ids_path`, `random_hex`, `ratchet_decrypt`, `ratchet_encrypt`, `ratchet_lock`, `read_encrypted`, `receive_ratchet_gift_wrap`, `save_account`, `save_friend_device`, `save_sessions`, `send_ratchet_envelope`, `session_config`, `session`, `sessions_path`, `store_session`, `to_olm_message`, `write_encrypted`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `DeviceAnnouncePayload`, `DeviceBundle`, `RatchetContent`, `RatchetMessagePayload`, `RatchetReceived`, `SessionStore`, `StoredSession`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`
// These functions are ignored (category: IgnoreBecauseOwnerTyShouldIgnore): `default`

/// A fresh random key for encrypting this module's local state at rest —
/// call once and persist the result via `flutter_secure_storage` (see this
/// module's doc comment), the same way `keys.rs`'s seed phrase is handled.
/// Deliberately not derived from the mnemonic: unlike every other secret in
/// this app, this key must differ per device, since (per this module's doc
/// comment) sharing ratchet state across devices is exactly what breaks it.
Future<String> generateLocalStorageKey() =>
    RustLib.instance.api.crateApiRatchetGenerateLocalStorageKey();

/// This device's announceable public key material (see [DeviceBundle]),
/// creating its Olm account if this device doesn't have one yet — call
/// before [announce_device].
Future<String> deviceIdentityPubkey({
  required String storageDir,
  required String localKey,
}) => RustLib.instance.api.crateApiRatchetDeviceIdentityPubkey(
  storageDir: storageDir,
  localKey: localKey,
);

/// The forward-secrecy device key bundle (see [DeviceBundle]) that
/// `friend_pubkey` last announced to us, if any — the UI uses this to
/// decide whether to offer/attempt a forward-secret send at all, and
/// otherwise treats it as opaque.
///
/// Anything unparseable is reported as "no device announced" rather than
/// handed back for a send to choke on: a stored announce predating the
/// [DeviceBundle] format is exactly that, and the friendly failure is to
/// fall back to ordinary (non-forward-secret) chat until that friend's app
/// re-announces, which it does on the next thread open.
Future<String?> friendDevicePubkey({
  required String storageDir,
  required String friendPubkey,
}) => RustLib.instance.api.crateApiRatchetFriendDevicePubkey(
  storageDir: storageDir,
  friendPubkey: friendPubkey,
);

/// Publishes this device's public key bundle to `friend_pubkey`, over the
/// existing mnemonic-derived channel (so it's authenticated/encrypted the
/// same way any other control rumor is) — call once per friend (idempotent
/// to call again; the friend's app just re-applies the same value, or
/// switches to a new one if this device was reinstalled).
Future<void> announceDevice({
  required String mnemonic,
  required String storageDir,
  required String friendPubkey,
  required String localKey,
}) => RustLib.instance.api.crateApiRatchetAnnounceDevice(
  mnemonic: mnemonic,
  storageDir: storageDir,
  friendPubkey: friendPubkey,
  localKey: localKey,
);

/// This device's forward-secret history with `friend_pubkey`, oldest
/// first — merge into [chat::load_chat_history]'s result for display. Only
/// ever grows via messages sent/received *by this specific device* (see
/// module doc comment) — a fresh device starts with none.
Future<List<RatchetChatMessage>> loadRatchetHistory({
  required String storageDir,
  required String localKey,
  required String friendPubkey,
}) => RustLib.instance.api.crateApiRatchetLoadRatchetHistory(
  storageDir: storageDir,
  localKey: localKey,
  friendPubkey: friendPubkey,
);

/// Hides a forward-secret message from this device's view only — there's
/// no signed retraction for ratchet messages (see module doc: only the
/// receiving device ever holds the plaintext, so there's nothing for a
/// friend's device to authenticate against), so unlike [chat]'s
/// hide/edit/unsend this can't be anything but local.
Future<void> hideRatchetMessage({
  required String storageDir,
  required String localKey,
  required String messageId,
}) => RustLib.instance.api.crateApiRatchetHideRatchetMessage(
  storageDir: storageDir,
  localKey: localKey,
  messageId: messageId,
);

/// Sends `content` to `friend_pubkey` with forward secrecy, over a Double
/// Ratchet session with their most-recently-announced device — fails with
/// a clear error if they haven't announced one yet (call
/// [friend_device_pubkey] first to check).
Future<void> sendRatchetMessage({
  required String mnemonic,
  required String storageDir,
  required String friendPubkey,
  required String localKey,
  required String content,
  String? replyTo,
}) => RustLib.instance.api.crateApiRatchetSendRatchetMessage(
  mnemonic: mnemonic,
  storageDir: storageDir,
  friendPubkey: friendPubkey,
  localKey: localKey,
  content: content,
  replyTo: replyTo,
);

/// Replaces the content of a message this device previously sent, both
/// locally and (via a fresh ratchet-encrypted `edit` envelope) for the
/// friend's copy of it.
Future<void> editRatchetMessage({
  required String mnemonic,
  required String storageDir,
  required String friendPubkey,
  required String localKey,
  required String messageId,
  required String newContent,
}) => RustLib.instance.api.crateApiRatchetEditRatchetMessage(
  mnemonic: mnemonic,
  storageDir: storageDir,
  friendPubkey: friendPubkey,
  localKey: localKey,
  messageId: messageId,
  newContent: newContent,
);

/// Unsends a message this device previously sent, both locally and (via a
/// fresh ratchet-encrypted `delete` envelope) for the friend's copy.
Future<void> deleteRatchetMessage({
  required String mnemonic,
  required String storageDir,
  required String friendPubkey,
  required String localKey,
  required String messageId,
}) => RustLib.instance.api.crateApiRatchetDeleteRatchetMessage(
  mnemonic: mnemonic,
  storageDir: storageDir,
  friendPubkey: friendPubkey,
  localKey: localKey,
  messageId: messageId,
);

/// A forward-secret message, already decrypted — exposed to the UI to be
/// merged into a friend's regular (non-forward-secret) history.
class RatchetChatMessage {
  final String id;
  final String friendPubkey;
  final String content;
  final PlatformInt64 createdAt;
  final bool isMine;
  final bool hidden;
  final bool isEdited;
  final bool isDeleted;
  final String? replyTo;

  const RatchetChatMessage({
    required this.id,
    required this.friendPubkey,
    required this.content,
    required this.createdAt,
    required this.isMine,
    required this.hidden,
    required this.isEdited,
    required this.isDeleted,
    this.replyTo,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      friendPubkey.hashCode ^
      content.hashCode ^
      createdAt.hashCode ^
      isMine.hashCode ^
      hidden.hashCode ^
      isEdited.hashCode ^
      isDeleted.hashCode ^
      replyTo.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RatchetChatMessage &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          friendPubkey == other.friendPubkey &&
          content == other.content &&
          createdAt == other.createdAt &&
          isMine == other.isMine &&
          hidden == other.hidden &&
          isEdited == other.isEdited &&
          isDeleted == other.isDeleted &&
          replyTo == other.replyTo;
}
