// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.4.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `default_relay_urls`, `relay_list_path`, `runtime`

/// The default set of public relays, used both as the fallback in
/// [load_relay_list] and to let the UI offer a "reset to defaults" action.
Future<List<String>> defaultRelays() =>
    RustLib.instance.api.crateApiRelayDefaultRelays();

/// Saves the relay list as JSON under `storage_dir`.
/// `storage_dir` must already exist (e.g. the app's documents directory,
/// resolved on the Dart side via path_provider).
Future<void> saveRelayList({
  required String storageDir,
  required List<String> urls,
}) => RustLib.instance.api.crateApiRelaySaveRelayList(
  storageDir: storageDir,
  urls: urls,
);

/// Loads the saved relay list, or a small set of default public relays if
/// none has been saved yet.
Future<RelayList> loadRelayList({required String storageDir}) =>
    RustLib.instance.api.crateApiRelayLoadRelayList(storageDir: storageDir);

/// Tries to open a WebSocket connection to each URL to check whether the
/// relay is currently reachable. Returns one bool per input URL, in order.
Future<List<bool>> checkRelayStatuses({required List<String> urls}) =>
    RustLib.instance.api.crateApiRelayCheckRelayStatuses(urls: urls);

/// The list of Nostr relay URLs this device publishes to / reads from.
class RelayList {
  final List<String> urls;

  const RelayList({required this.urls});

  @override
  int get hashCode => urls.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RelayList &&
          runtimeType == other.runtimeType &&
          urls == other.urls;
}
