// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.4.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `fetch_latest_backup_event`, `fetch_one`, `publish_one`, `publish_to_relays`, `runtime`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `BackupPayload`

/// Encrypts the given account info (NIP-44, to self) and publishes it to
/// `relay_urls` as a kind-30078 parameterized-replaceable event, signed with
/// the Nostr keys derived from `mnemonic` (NIP-06). The seed phrase itself
/// is never transmitted — only the deterministically-derived public
/// identity and the encrypted payload.
Future<void> publishAccountBackup({
  required String mnemonic,
  required List<String> relayUrls,
  required String displayName,
  required String statusMessage,
  required PlatformInt64 updatedAt,
}) => RustLib.instance.api.crateApiSyncPublishAccountBackup(
  mnemonic: mnemonic,
  relayUrls: relayUrls,
  displayName: displayName,
  statusMessage: statusMessage,
  updatedAt: updatedAt,
);

/// Fetches and decrypts the newest account backup for `mnemonic`'s derived
/// identity across `relay_urls`. Returns `None` if no relay has one yet.
Future<RemoteAccount?> fetchAccountBackup({
  required String mnemonic,
  required List<String> relayUrls,
}) => RustLib.instance.api.crateApiSyncFetchAccountBackup(
  mnemonic: mnemonic,
  relayUrls: relayUrls,
);

/// Requests relays to erase this account's backup event (NIP-09 deletion
/// request). A no-op if no backup exists yet.
Future<void> deleteAccountBackup({
  required String mnemonic,
  required List<String> relayUrls,
}) => RustLib.instance.api.crateApiSyncDeleteAccountBackup(
  mnemonic: mnemonic,
  relayUrls: relayUrls,
);

/// Account info decrypted from a relay-hosted backup.
class RemoteAccount {
  final String displayName;
  final String statusMessage;
  final PlatformInt64 updatedAt;

  const RemoteAccount({
    required this.displayName,
    required this.statusMessage,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      displayName.hashCode ^ statusMessage.hashCode ^ updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RemoteAccount &&
          runtimeType == other.runtimeType &&
          displayName == other.displayName &&
          statusMessage == other.statusMessage &&
          updatedAt == other.updatedAt;
}
